---
- name: Add Barman apt key
  when: barman_apt_custom_repo_enabled
  ansible.builtin.get_url:
    url: "{{ barman_apt_key_url }}"
    dest: /etc/apt/keyrings/apt.postgresql.org.asc
    mode: "0644"
  become: true

- name: Add Barman repository
  when: barman_apt_custom_repo_enabled
  ansible.builtin.apt_repository:
    repo: "{{ barman_apt_repo }}"
  become: true

- name: Install Barman package
  ansible.builtin.package:
    name: barman
    state: "{{ barman_package_state }}"
  become: true

- name: Install dependencies for s3 sync
  when: barman_pg_servers | selectattr('backup_schedule.s3_sync', 'mapping') | list | length > 0
  block:
    # TODO: Replace global installation of AWS CLI by a dedicated one
    # specifically for Barman. This will solve two problems:
    # - AWS CLI can be safely removed when Barman is uninstalled
    # - We can support Ubuntu 24.04 which doesn't have AWS CLI in the default
    #   repositories
    - name: Install awscli
      ansible.builtin.package:
        name: awscli
      become: true
    - name: Install barman s3 scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
      loop:
        - barman-aws-s3-sync.sh
        - barman-aws-s3-stats.sh
      become: true
