---
- name: Add Barman apt key
  when: barman_apt_custom_repo_enabled
  ansible.builtin.apt_key:
    url: "{{ barman_apt_key_url }}"
  become: yes

- name: Add Barman repository
  when: barman_apt_custom_repo_enabled
  ansible.builtin.apt_repository:
    repo: "{{ barman_apt_repo }}"
  become: yes

- name: Install Barman package
  ansible.builtin.package:
    name: barman
    state: "{{ barman_package_state }}"
  become: yes

- name: Install dependencies for s3 sync
  when: barman_pg_servers | selectattr('backup_schedule.s3_sync', 'mapping') | list | length > 0
  block:
  - name: Install awscli
    ansible.builtin.package:
      name: awscli
    become: yes
  - name: Install barman s3 scripts
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: "0755"
    loop:
    - barman-aws-s3-sync.sh
    - barman-aws-s3-stats.sh
    become: yes
