---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:22.04}
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
        barman_user: barman
        barman_pass: BARMANPASS
        barman_streaming_user: streaming_barman
        barman_streaming_pass: STREAMINGPASS
        barman_service_mgr: sysv  # Workaround for https://github.com/ansible/ansible/issues/74480
verifier:
  name: ansible
